### ISSUE TITLE
LIBXML_NO_XXE flag set incorrectly

### ISSUE THREAD

**Issue by matthew-8925** [simplesamlphp/xml-common#35]
Hi, 

Looking at this, it seems a "not equals" operator is used with LIBXML_NO_XXE instead of a bitwise OR, so won't have the intended effect.

https://github.com/simplesamlphp/xml-common/blob/9cf986ee7d97c02feb992c78f51024f45b068c19/src/DOMDocumentFactory.php#L57

Seems to have come from here,
[7523ee8bc346b80ec0c02e6db5a82f78f8b07bba](https://github.com/simplesamlphp/xml-common/commit/7523ee8bc346b80ec0c02e6db5a82f78f8b07bba)

Not 100% a security issue, as LIBXML_NO_XXE isn't commonly available and it's the other mitigations prevent XXE.

**Comment by thijskh** [comment]
Yes, you are of course right. I reviewed that but the difference is so subtle that I overlooked it. Thanks for reporting!

It's indeed a defense in depth measure, but of course for that role it should actually do something.
